version: 2
jobs:
  build:
    docker:
      - image: ipfs/ci-websites
        environment:
          DEBUG: "true"
    steps:
      - checkout
      - run:
          command: make install
      - run:
          command: make build
      - persist_to_workspace:
          root: .
          paths:
            - public

  deploy:
    docker:
      - image: olizilla/ipfs-dns-deploy:latest
        environment:
          DOMAIN: zh-cn.help
          BUILD_DIR: public
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - b0:6b:cf:e8:72:36:d0:35:d5:bf:eb:9f:4c:f4:a6:2b
      - checkout:
          path: /tmp/workspace/repo
      - run:
          name: Deploy website to IPFS
          command: |
            if [ "$CIRCLE_BRANCH" == "gh-pages" ] ; then
              exit
            fi

            cd /tmp/workspace/repo

            git checkout gh-pages

            mv -f /tmp/workspace/$BUILD_DIR/* /tmp/workspace/repo

            git add .

            git commit -m "Circle CI build $CIRCLE_BUILD_NUMBER"

            git push origin gh-pages

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
